/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImplantsRouteImport } from './routes/implants'
import { Route as AlignersAndBracesRouteImport } from './routes/aligners-and-braces'
import { Route as IndexRouteImport } from './routes/index'

const ImplantsRoute = ImplantsRouteImport.update({
  id: '/implants',
  path: '/implants',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignersAndBracesRoute = AlignersAndBracesRouteImport.update({
  id: '/aligners-and-braces',
  path: '/aligners-and-braces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aligners-and-braces': typeof AlignersAndBracesRoute
  '/implants': typeof ImplantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aligners-and-braces': typeof AlignersAndBracesRoute
  '/implants': typeof ImplantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aligners-and-braces': typeof AlignersAndBracesRoute
  '/implants': typeof ImplantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aligners-and-braces' | '/implants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aligners-and-braces' | '/implants'
  id: '__root__' | '/' | '/aligners-and-braces' | '/implants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignersAndBracesRoute: typeof AlignersAndBracesRoute
  ImplantsRoute: typeof ImplantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/implants': {
      id: '/implants'
      path: '/implants'
      fullPath: '/implants'
      preLoaderRoute: typeof ImplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aligners-and-braces': {
      id: '/aligners-and-braces'
      path: '/aligners-and-braces'
      fullPath: '/aligners-and-braces'
      preLoaderRoute: typeof AlignersAndBracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignersAndBracesRoute: AlignersAndBracesRoute,
  ImplantsRoute: ImplantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
